CREATE TABLE IF NOT EXISTS cards (
	id SERIAL PRIMARY KEY,
	cert_number VARCHAR(32) UNIQUE NOT NULL,
	card_name VARCHAR(255) NOT NULL,
	card_set VARCHAR(255),
	card_number VARCHAR(64),
	current_grade VARCHAR(32),
	psa9_price NUMERIC(10,2),
	psa10_price NUMERIC(10,2),
	image_url TEXT,
	created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);